# Generated by Django 4.1.2 on 2022-11-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=50, verbose_name='Mật khẩu')),
                ('fullname', models.CharField(blank=True, max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.CharField(max_length=200, verbose_name='Nội dung')),
            ],
        ),
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameItem', models.CharField(max_length=50, verbose_name='Tên kiểu đồ')),
                ('amountLost', models.IntegerField(verbose_name='Số lượng mất')),
                ('amountPick', models.IntegerField(verbose_name='Số lượng nhặt được')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, verbose_name='Người gửi')),
                ('receiver', models.CharField(max_length=50, verbose_name='Người nhận')),
                ('content', models.CharField(max_length=50, verbose_name='Nội dung')),
                ('time', models.DateTimeField(verbose_name='Thời gian')),
                ('status', models.CharField(blank=True, choices=[('W', 'Waiting'), ('S', 'Success'), ('F', 'Failed')], max_length=50, verbose_name='Trạng thái tin nhắn')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
    ]
