# Generated by Django 4.1.2 on 2022-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
