# Generated by Django 4.1.2 on 2022-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='textInfo',
            new_name='postInfo',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('W', 'Waiting'), ('S', 'Success'), ('F', 'Failed')], max_length=50, verbose_name='Trạng thái tin nhắn'),
        ),
    ]
