# Generated by Django 4.1.2 on 2022-11-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_content_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung'),
        ),
    ]
