# Generated by Django 4.1.1 on 2022-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_textinfo_item_postinfo_alter_item_typeitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='fullname',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='Vu hoang an', max_length=50, verbose_name='Họ tên'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên'),
        ),
    ]
