# Generated by Django 4.1.2 on 2022-11-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm thất lạc đồ'),
        ),
    ]
