# Generated by Django 4.1.1 on 2022-10-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_textinfo_item_postinfo_alter_message_status'),
        ('app', '0003_rename_fullname_message_sender_message_receiver_and_more'),
    ]

    operations = [
    ]
