# Generated by Django 4.1.2 on 2022-11-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_postinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ảnh đồ vật ( nếu có)'),
        ),
    ]
