# Generated by Django 4.1.2 on 2022-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
    ]
