# Generated by Django 4.1.2 on 2022-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_email_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='typeItem',
            field=models.CharField(blank=True, choices=[('ID', 'Ví/Giấy tờ'), ('PET', 'Thú cưng'), ('PEOPLE', 'Người'), ('ED', 'Điện thoại/Tablet/Laptop'), ('KEY', 'Chìa khóa'), ('TRANSPORT', 'Xe máy/Ô tô'), ('OTHER', 'Đồ vật khác')], max_length=10, null=True, verbose_name='Loại đồ vật'),
        ),
    ]
