# Generated by Django 4.1.2 on 2022-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_typeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
    ]
