# Generated by Django 4.1.2 on 2022-11-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng tin'),
        ),
    ]
